// <auto-generated />
using System;
using ConfiguringModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConfiguringModels.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230307083424_AddWorkPropInUserClass4")]
    partial class AddWorkPropInUserClass4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("ConfiguringModels.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CompanyUser", (string)null);
                });

            modelBuilder.Entity("ConfiguringModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("UserId");

                    b.HasIndex("Gender")
                        .HasDatabaseName("GenderUsers");

                    b.HasIndex("WorkId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ConfiguringModels.User", b =>
                {
                    b.HasOne("ConfiguringModels.Company", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId");

                    b.Navigation("Work");
                });
#pragma warning restore 612, 618
        }
    }
}
